Update gen_sshkey

diff --git a/module/gen_sshkey b/module/gen_sshkey
--- a/module/gen_sshkey
+++ b/module/gen_sshkey
@@ -3,12 +3,14 @@
 function pkg_install {
   MODULENAME=$1
   echo "${MODULENAME}"
-  #INSTALLED=`dpkg --get-selections | grep "${MODULENAME}" | grep "install" | wc -l`
-  #apt-get install -fy ${MODULENAME}
-}  
+  INSTALLED=`dpkg --get-selections | grep "${MODULENAME}" | grep "install" | wc -l`
+  if [ "$INSTALLED" -eq "0" ]; then
+    [[ "$(id -u)" -eq 0 ]] || (echo "FATAL: Root privilege is required."; exit 1)
+    apt-get install -fy ${MODULENAME}
+  fi
+}
 
 pkg_install python-crypto
 
-
-wget -qO- https://github.com/ziozzang/home-server/blob/master/module/gen_rsakey.py | python - $1
+wget -qO- https://raw.github.com/ziozzang/home-server/master/module/gen_rsakey.py | python - $1
 
